### PR TITLE
Add database schema, data, and queries for vet clinic animals

### PR DESCRIPTION
**Pull request by Oscar-Espinoza**
This pull request adds a database schema, inserts data into the database, and provides SQL queries for a vet clinic's animal records. The database schema includes an animals table with columns for id, name, date_of_birth, escape_attempts, neutered, and weight_kg. The data includes four animal records with names, birth dates, weights, neuter status, and escape attempts. The SQL queries allow for easy filtering and retrieval of animal records based on criteria such as name, birth date, weight, neuter status, and escape attempts. Screenshots of the query results are also included.

Please review and merge these changes as appropriate. Thank you!

first-query

second-queries

### CODE REVIEW

**Review by t-yanick — COMMENTED** [review]
Hi @Oscar-Espinoza , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, whose ReadMe has not been personalized. Add the various section of your ReadMe. Ensure the the Live demo link is working or you use the text `Coming soon ...`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by t-yanick — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED

Hi @Oscar-Espinoza , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  SQL statements put the correct files
:heavy_check_mark: Repo generated using given template

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Great job working on this milestone. As per project requirements, you are supposed to add screenshots of queries results to you pull request description. At the moment, that is missing. Kindly at that and request for a re-review.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Davidosky007 — CHANGES_REQUESTED** [review]
Hi @Oscar-Espinoza 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Good looking readme file 👍 
* Descriptive commit messages 👍 

 ## Required Changes ♻️
* As stated by the previous CR kindly add screenshots of your queries to your PR description example below 👇 add the screenshots like you will add your PR summary 
image

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Oscar,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉 

## Highlights 👍
- Correctly implemented requested changes!

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
- You used incorrect git-flow/ GitHub flow for this project. Kindly note that the merge request for this project should flow from **from feature into development**. Kindly note this important step for subsequent projects.
- Kindly describe between 1-3 key features of the application.
- Kindly ensure that the _Future Features_ section of your ReadMe includes 1-3 potential features to be added later.
- Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. Similarly, kindly also remove guide notes for _license_ creation under the _license_ section.
- Kindly endeavor to fill the FAQ section with at least 2 Q&A(s), or optionally remove this section.
- Kindly ensure to remove redundant contributor details under the Author section.

Implementing the above change(s) will make your ReadMe/ repository stand out even better! 😉

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
